### ISSUE TITLE
[REFACTORING] Server, Client 구조 리팩토링

### ISSUE THREAD

**Issue by AhnJoonSung** [SPARTA42CLUB/Webserver#13]
### 작업 설명

- client 소켓에 대한 처리 로직을 Client 객체에 위임하게 변경. 
- Server 코드 정리

### 수정 이유

Client 객체의 역할이 애매해서 명확하게 정리

**Comment by fing9** [comment]
### 중간 정리
- Client 객체의 필요성이 모호함에 따라 Client 객체 제거
  - 이에 따른 변경으로 Client 소켓과 그에 연결된 Server의 Config를 HashMap으로 관리하게 변경
- Server의 책임을 분리할 필요성이 대두되었으나 명확한 해결책은 아직 제시되지 못 함

**Comment by AhnJoonSung** [comment]
해결 완료.
